name: env_clustallite
channels:
    - conda-forge
    - bioconda
    - nodefaults
dependencies:
    - python
    - biopython
    - numpy
    - pandas
    - argparse
    - joblib
    - pycodestyle
    - pydocstyle
    - black
    - pylint