name: env_clustallite
channels:
    - conda-forge
    - bioconda
    - nodefaults
dependencies:
    - python=3.11.5
    - biopython
    - numpy
    - pandas
    - argparse
    - joblib
    - pycodestyle
    - pydocstyle
    - black
    - pylint